# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    desc "Archive the App"
    build_app(scheme: "MyResume (iOS)", workspace: "MyResume.xcworkspace")
  end

  lane :test do
    desc "Unit tests"
    #run_tests
    
    run_tests(
      workspace: "MyResume.xcworkspace",
      scheme: "MyResume (iOS)",
      device: "iPhone 11",
      clean: false
    )
    end

end
